Added swedbank csv provider.
emokykla/payment-statement-parser-bundle pull request #3
Opened 2021-02-04 18:58 UTC by aurelijusrozenas

2021-02-08 09:57 UTC, aphex008 requested changes

2021-02-08 09:57 UTC, aphex008 commented on src/Factory/SwedbankCsv/SwedbankCsvPaymentRowModelFactory.php
> +    /**
Laba diena

2021-02-08 09:58 UTC, aphex008 requested changes

2021-02-08 09:58 UTC, aphex008 commented on src/Factory/SwedbankCsv/SwedbankCsvPaymentRowModelFactory.php
> +use function sprintf;
Test comment

2021-02-08 10:18 UTC, aphex008 commented
Tai pagrindinis pull requesto reviewinimo minusas - neradau kaip pakomentuoti nepakeistą failą. T.y. rodo tik changed.

2021-02-08 10:19 UTC, aphex008 requested changes
Viskas daugiau mažiau OK, tik būtų gerai, jei įmergintum mano mac configo PR.

2021-02-08 10:19 UTC, aphex008 commented on docs/SwedbankCsv/swedbankCsvPaymentExportImport.md
> +- column delimiter - comma
Šitas lyg ir dubliuoja, bet pilnai nepadengia to kas yra servise
```php
 $sourceString = $this->csvEncoder->encode(
                $row,
                CsvEncoder::FORMAT,
                [
                    CsvEncoder::DELIMITER_KEY => ',',
                    CsvEncoder::ENCLOSURE_KEY => '"',
                    CsvEncoder::KEY_SEPARATOR_KEY => '.',
                    CsvEncoder::NO_HEADERS_KEY => true,
                    CsvEncoder::AS_COLLECTION_KEY => true,
                ]
            );
```

Gal referencint arba iškelt į konstantą ir referencint į ten?

2021-02-08 10:19 UTC, aphex008 commented on src/Factory/SwedbankCsv/SwedbankCsvPaymentRowModelFactory.php
> +    public function get(string $lineId, array $row, string $sourceString): AbstractSwedbankCsvPaymentRowModel
Sakyčiau arba line number, arba record id?

2021-02-08 10:19 UTC, aphex008 commented on src/Factory/SwedbankCsv/SwedbankCsvPaymentRowModelFactory.php
> +                if ($recordType) {
Neatrodo redundand? Neužtektų vieno abiems keisams? T.y. record tupe ``null`` gali lygiai taip pat naudoti paskutinį throw. Tik jame reiktų išvesti ir tipą. Nes dabar šioje klaidoje matysi kad null. O žemiau esančioje klaidoje nematysi kokio tipo nemoka sukurti.

2021-02-08 10:19 UTC, aphex008 commented on src/Model/SwedbankCsv/AbstractSwedbankCsvPaymentRowModel.php
> +
Gal verta pridėti komentą RECORD_TYPE sekcijai?

2021-02-08 10:19 UTC, aphex008 commented on src/Model/SwedbankCsv/AbstractSwedbankCsvPaymentRowModel.php
> +            'accountNumber',
Entičiuose visai sėkmingai naudojame konstantas PROPERTY_ACCOUNT_NUMBER, kad renaminant nereiktų searchinti usages visam kodel. Ar čia nevertėtų to paties daryti?

2021-02-08 10:19 UTC, aphex008 commented on src/Service/SwedbankCsv/SwedbankCsvPaymentDeserializerService.php
> +    public function explodePaymentsCsv(string $content): array
decodePayumentCsv?

2021-02-10 05:43 UTC, aurelijusrozenas commented
> Viskas daugiau mažiau OK, tik būtų gerai, jei įmergintum mano mac configo PR.

normaliai atsakyti prie komentaro galima tik kai pakomentuoji pakeistą failą + iš IDE to net neina padaryti.

2021-02-10 05:44 UTC, aurelijusrozenas commented on src/Service/SwedbankCsv/SwedbankCsvPaymentDeserializerService.php
> +    public function explodePaymentsCsv(string $content): array
manau kad explode tau aiškiau pasako, ką gausi. Nes kitu atveju tiesiog pavadinčiau deserialize.

2021-02-10 05:59 UTC, aurelijusrozenas commented on src/Factory/SwedbankCsv/SwedbankCsvPaymentRowModelFactory.php
> +    public function get(string $lineId, array $row, string $sourceString): AbstractSwedbankCsvPaymentRowModel
lineId as in lineIdentificator, kurį gali susiformatuoti kaip nori, pvz., line-1, nes taip tau yra aiškiau išvedant pranešimus. Tai nėra line number dėl tos priežasties. Tai nėra record id, nes tai surišta su csv eilute ir kitaip negali būti.

2021-02-10 06:02 UTC, aurelijusrozenas commented on src/Factory/SwedbankCsv/SwedbankCsvPaymentRowModelFactory.php
> +                if ($recordType) {
1. Nemanau, kad čia labai ką nors laimėtume padarydami DRY
2. Stengiausi, kad pranešimus būtų maksimaliai aiškus, ir nereiktų eiti žvejoti per bundle kodą, kad surastum, kad čia beveik tas tik biški kitaip
3. <label>won't fix</label>

2021-02-10 06:03 UTC, aurelijusrozenas commented on src/Model/SwedbankCsv/AbstractSwedbankCsvPaymentRowModel.php
> +
Tipo `Indicates type of the record`? Tokio tai tikrai nereikia. Ką dar galima pridėti?

2021-02-11 11:37 UTC, merged